### ISSUE TITLE
Getting NotImplementedError if I try any image dataset

### ISSUE THREAD

**Issue by tremblerz** [chrvt/denoising-normalizing-flow#1]
Here is the error log. I tried GAN-2d,64d and CelebA dataset. Almost everything is unmodified except 

```
00:36 __main__             INFO    Hi!
00:36 __main__             INFO    Training model dnf_2_gan2d_paper with algorithm dnf on data set gan2d
00:36 architectures.create INFO    Creating manifold flow for image data with 4 levels and 5 steps per level in the outer transformation, 6 layers in the inner transformation, transforms rq-coupling / rq-coupling, None context features
00:36 manifold_flow.flows. INFO    Model has 16.4 M parameters (16.4 M trainable) with an estimated size of 65.7 MB
00:36 manifold_flow.flows. INFO      Outer transform: 16.2 M parameters
00:36 manifold_flow.flows. INFO      Inner transform: 0.3 M parameters
00:36 training.trainer     INFO    Training on 8 GPUS with single precision
00:36 __main__             INFO    Starting training denoising flow on NLL
Traceback (most recent call last):
  File "train.py", line 702, in <module>
    learning_curves = train_model(args, dataset, model, simulator)
  File "train.py", line 637, in train_model
    learning_curves = train_dnf(args, dataset, model, simulator)
  File "train.py", line 512, in train_dnf
    learning_curves = trainer.train(
  File "/tremblerz/denoising-normalizing-flow/experiments/training/trainer.py", line 322, in train
    loss_train, loss_val, loss_contributions_train, loss_contributions_val = self.epoch(
  File "/tremblerz/denoising-normalizing-flow/experiments/training/trainer.py", line 398, in epoch
    self.first_batch(batch_data)
  File "/tremblerz/denoising-normalizing-flow/experiments/training/trainer.py", line 583, in first_batch
    self.model(x[: x.shape[0] // torch.cuda.device_count(), ...])
  File "/tremblerz/.torchP2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/tremblerz/denoising-normalizing-flow/experiments/../manifold_flow/flows/manifold_flow.py", line 59, in forward
    else: x_reco, inv_log_det_inner, inv_log_det_outer, inv_jacobian_outer, h_manifold_reco = self._decode(u, mode=mode, context=context)
  File "/tremblerz/denoising-normalizing-flow/experiments/../manifold_flow/flows/manifold_flow.py", line 143, in _decode
    x, inv_jacobian_outer = self.outer_transform.inverse(h, full_jacobian=True, context=context if self.apply_context_to_outer else None)
  File "/tremblerz/denoising-normalizing-flow/experiments/../manifold_flow/transforms/base.py", line 84, in inverse
    return self._cascade(inputs, funcs, context, full_jacobian)
  File "/tremblerz/denoising-normalizing-flow/experiments/../manifold_flow/transforms/base.py", line 56, in _cascade
    outputs, jacobian = func(inputs, context, full_jacobian=True)
  File "/tremblerz/denoising-normalizing-flow/experiments/../manifold_flow/transforms/base.py", line 84, in inverse
    return self._cascade(inputs, funcs, context, full_jacobian)
  File "/tremblerz/denoising-normalizing-flow/experiments/../manifold_flow/transforms/base.py", line 56, in _cascade
    outputs, jacobian = func(inputs, context, full_jacobian=True)
  File "/tremblerz/denoising-normalizing-flow/experiments/../manifold_flow/transforms/partial.py", line 74, in inverse
    transform_split, transform_logabsdet = self.transform.inverse(transform_split, context=context, full_jacobian=full_jacobian)
  File "/tremblerz/denoising-normalizing-flow/experiments/../manifold_flow/transforms/base.py", line 84, in inverse
    return self._cascade(inputs, funcs, context, full_jacobian)
  File "/tremblerz/denoising-normalizing-flow/experiments/../manifold_flow/transforms/base.py", line 56, in _cascade
    outputs, jacobian = func(inputs, context, full_jacobian=True)
  File "/tremblerz/denoising-normalizing-flow/experiments/../manifold_flow/transforms/nonlinearities.py", line 78, in inverse
    raise NotImplementedError
NotImplementedError
```

**Comment by chrvt** [comment]
What config did you use? Did you try with 1 GPU instead of 8?

**Comment by tremblerz** [comment]
I tried `train_dnf_celeba.config` and gan2d, 64d.
Intrestingly, seems to be working with a single GPU. I will try to investigate why `inverse` of `full_jacobian` is required for 8 GPUs but not on a 1 GPU setup. Thanks for suggesting that.

**Comment by chrvt** [comment]
yes, that's strange. I will have a closer look when I have some time. Thanks for raising the issue and let me know if you could solve it :-)

**Comment by tremblerz** [comment]
Spotted the bug at this [line](https://github.com/chrvt/denoising-normalizing-flow/blob/master/experiments/training/trainer.py#L577). The function `first_batch` should be passing `forward_kwargs` to the forward function. Seems to be an issue with the Manifold flow repo too. Works after making this fix.
Happy to send a PR if you are interested.

**Comment by chrvt** [comment]
Great! Yes please do send PR. Thanks a lot.

**Comment by chrvt** [comment]
PR merged solving the issue.
